services:
  - type: web
    name: uzum-market-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: SHOP_NAME
        value: UZUM MARKET
      - key: SUPPORT
        value: "@Uzum_Amazon_support"
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CARD_NUMBER
        sync: false
      - key: CARD_HOLDER
        sync: false
      - key: DB_NAME
        value: uzum_market.db
      - key: CHANNEL_ID
        value: "@UZUM_AMAZON"

  - type: worker
    name: uzum-market-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: SHOP_NAME
        value: UZUM MARKET
      - key: SUPPORT
        value: "@Uzum_Amazon_support"
      - key: DB_NAME
        value: uzum_market.db
      - key: CHANNEL_ID
        value: "@UZUM_AMAZON"
